############################################################
# Global values
############################################################
global:
  envs: {
    RELEASE_NAME: silver-penguin,
    RELEASE_HOST: ping-devops.com
  }

  addReleaseNameToResource: prepend

  ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
       #nginx example
       nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
       kubernetes.io/ingress.class: "nginx-public"

  image:
    repository: pingidentity
    name:
    tag: "2108"
    pullPolicy: IfNotPresent

  license:
    secret:
      devOps: devops-secret

  
#############################################################
# Images
#############################################################

# pingfederate-admin
pingfederate-admin:
  enabled: true
  name: pingfederate-admin
  image:
    name: pingfederate

  container:
    resources:
      requests:
        cpu: 0
        memory: 1Gi
      limits:
        cpu: 2
        memory: 4Gi

  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        volumes:
          out-dir:
            persistentVolumeClaim:
              resources:
                requests:
                  storage: 8Gi

  envs:
    SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
    SERVER_PROFILE_PATH: server-profiles/pingfederate
    OPERATIONAL_MODE: STANDALONE
    PF_CONSOLE_AUTHENTICATION: NATIVE

  services:
    https:
      servicePort: 9999
      containerPort: 9999
      ingressPort: 443
      dataService: true
    engine:
      servicePort: 9031
      containerPort: 9031
      ingressPort: 443
      dataService: true

  ingress:
    hosts:
      - host: pingfederate-admin._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
      - host: pingfederate-engine._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: engine
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingfederate-admin._defaultDomain_
          - pingfederate-engine._defaultDomain_

# pingfederate-engine 
# pingfederate-engine:
#   enabled: false
#   name: pingfederate-engine
#   image:
#     name: pingfederate

#   container:
#     resources:
#       requests:
#         cpu: 0
#         memory: 1Gi
#       limits:
#         cpu: 2
#         memory: 4Gi
#     waitFor:
#       pingfederate-admin:
#         service: https
#         timeoutSeconds: 300

#   envs:
#     SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
#     SERVER_PROFILE_PATH: server-profiles/pingfederate
# #     PF_ADMIN_PORT: "9999"

#   services:
#     https:
#       servicePort: 9031
#       containerPort: 9031
#       ingressPort: 443
#       dataService: true
#     clusterbind:
#       servicePort: 7600
#       containerPort: 7600
#       clusterService: true
#     clusterfail:
#       servicePort: 7700
#       containerPort: 7700
#       clusterService: true
#     clusterServiceName: pingfederate-cluster

#   ingress:
#     hosts:
#       - host: pingfederate-engine._defaultDomain_
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             serviceName: https
#     tls:
#       - secretName: _defaultTlsSecret_
#         hosts:
#           - pingfederate-engine._defaultDomain_

# pingdirectory
pingdirectory:
  enabled: true
  name: pingdirectory
  image:
    name: pingdirectory

  container:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi

    terminationGracePeriodSeconds: 300

  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        volumes:
          out-dir:
            persistentVolumeClaim:
              resources:
                requests:
                  storage: 8Gi

  envs:
    SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
    SERVER_PROFILE_PATH: server-profiles/pingdirectory
    MAKELDIF_USERS: "10"

  services:
    ldap:
      servicePort: 389
      containerPort: 1389
      dataService: true
    ldaps:
      servicePort: 636
      containerPort: 1636
      dataService: true
      clusterService: true
    https:
      servicePort: 443
      containerPort: 1443
      ingressPort: 443
      dataService: true
    clusterServiceName: pingdirectory-cluster

  ingress:
    hosts:
      - host: pingdirectory._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingdirectory._defaultDomain_


#############################################################
# pingaccess-admin values
#############################################################
pingaccess-admin:
  enabled: true
  name: pingaccess-admin
  image:
    name: pingaccess

  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingaccess
    # SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
    # SERVER_PROFILE_PATH: server-profiles/pingaccess
    OPERATIONAL_MODE: STANDALONE

  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        volumes:
          out-dir:
            persistentVolumeClaim:
              resources:
                requests:
                  storage: 4Gi

  services:
    https:
      servicePort: 9000
      containerPort: 9000
      ingressPort: 443
      dataService: true
    engine:
      servicePort: 3000
      containerPort: 3000
      ingressPort: 443
      dataService: true

  ingress:
    hosts:
      - host: pingaccess-admin._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
      - host: pingaccess-engine._defaultDomain_
        paths:
        - path: /
          backend:
            serviceName: engine
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingaccess-admin._defaultDomain_
          - pingaccess-engine._defaultDomain_

# pingaccess-engine values
# pingaccess-engine:
#   enabled: false
#   name: pingaccess-engine
#   image:
#     name: pingaccess

#   container:
#     resources:
#       requests:
#         cpu: 0
#         memory: 1Gi
#       limits:
#         cpu: 2
#         memory: 4Gi
#     waitFor:
#       pingaccess-admin:
#         service: https
#         timeoutSeconds: 300

#   envs:
#     SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
#     SERVER_PROFILE_PATH: getting-started/pingaccess
#     #SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
#     #SERVER_PROFILE_PATH: server-profiles/pingaccess

#   services:
#     https:
#       servicePort: 3000
#       containerPort: 3000
#       ingressPort: 443
#       dataService: true

#   ingress:
#     hosts:
#       - host: pingaccess-engine._defaultDomain_
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             serviceName: https
#     tls:
#       - secretName: _defaultTlsSecret_
#         hosts:
#           - pingaccess-engine._defaultDomain_

# pingdataconsole
pingdataconsole:
  enabled: true
  name: pingdataconsole
  image:
    name: pingdataconsole

  container:
    resources:
      requests:
        cpu: 0
        memory: .5Gi
      limits:
        cpu: 2
        memory: 2Gi

  defaultLogin:
    server:
      host: pingdirectory-cluster
      port: 636
    username: administrator

  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingdataconsole

  services:
    https:
      containerPort: 8443
      servicePort: 8443
      ingressPort: 443
      dataService: true

  ingress:
    hosts:
      - host: pingdataconsole._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingdataconsole._defaultDomain_