############################################################
# Ping Identity DevOps values.yaml
############################################################
# The yaml is seperated into 2 major sections:
#  - global - Represents the base set of values that will
#             be used for each product, if that product
#             doesn't override the global values.
#
#  - image  - For every image/product, the values will
#             be merged with the global settings, and
#             take precedence.
############################################################

############################################################
# Global values
############################################################
global:
  ############################################################
  # envs - Environment variables listed will be added to the
  #        global-env-vars configmap.
  #
  # NOTE: Environment variables listed at the global: level
  #       will actually end up being listed twice in the
  #       configmaps (i.e. global-env-vars and product-env-vars)
  ############################################################
  envs: {
    RELEASE_NAME: silver-penguin,
    RELEASE_HOST: ping-devops.com
  }

  addReleaseNameToResource: prepend

  ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: ping-devops.com
    defaultTlsSecret:
    annotations:
       #nginx example
       nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
       kubernetes.io/ingress.class: "nginx-public"

  image:
    repository: pingidentity
    name:
    tag: "2108"
    pullPolicy: IfNotPresent

    ############################################################
    # Probes
    #
    # Probes have a number of fields that you can use to more precisely control the
    # behavior of liveness and readiness checks.
    #
    # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
    ############################################################
    probes:
      livenessProbe:
        exec:
          command:
            - /opt/liveness.sh
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      readinessProbe:
        exec:
          command:
            - /opt/readiness.sh
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 4
      startupProbe:
        exec:
          command:
            - /opt/liveness.sh
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 90

  ############################################################
  # Licensing
  #
  # license.secret.devOps
  #    Identify the k8s secret to keep the DevOps USER/KEY if used during deployement.
  #
  # NOTE: licenseSecretName can be set in deploying chart values to specify a secret
  #       with actual product license.  This would override the DevOps secret.
  #
  # Using pingctl utility (brew install pingctl):
  #    pingctl k8s generate devops-secret | kubectl apply -f -
  ############################################################
  license:
    secret:
      devOps: devops-secret

  
#############################################################
# Image/Product values
#############################################################

#############################################################
# pingfederate-admin values
#############################################################
pingfederate-admin:
  enabled: true
  name: pingfederate-admin
  image:
    name: pingfederate

  container:
    resources:
      requests:
        cpu: 0
        memory: 1Gi
      limits:
        cpu: 2
        memory: 4Gi

  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        volumes:
          out-dir:
            persistentVolumeClaim:
              resources:
                requests:
                  storage: 8Gi

  envs:
    SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
    SERVER_PROFILE_PATH: server-profiles/pingfederate
    OPERATIONAL_MODE: STANDALONE
    #PF_CONSOLE_AUTHENTICATION: NATIVE
    #PF_OIDC_CLIENT_ID: 087f2dcb-e4f5-42c8-a246-e440d9f51624
    #PF_OIDC_CLIENT_SECRET: EMfze~JXXo.UhWoiXq.a3Xm~nN~Bga2EmzuCVLFcHO43LMi_qsPTC32OzfL8UbMI
    #PF_OIDC_AUTHORIZATION_ENDPOINT: https://auth.pingone.com/4d03914a-5c4a-4fd2-8ebd-f97c277373b5/as/authorize
    #PF_OIDC_TOKEN_ENDPOINT: https://auth.pingone.com/4d03914a-5c4a-4fd2-8ebd-f97c277373b5/as/token
    #PF_OIDC_USER_INFO_ENDPOINT: https://auth.pingone.com/4d03914a-5c4a-4fd2-8ebd-f97c277373b5/as/userinfo
    #PF_OIDC_END_SESSION_ENDPOINT: https://auth.pingone.com/4d03914a-5c4a-4fd2-8ebd-f97c277373b5/as/revoke
    #PF_OIDC_ISSUER: https://auth.pingone.com/4d03914a-5c4a-4fd2-8ebd-f97c277373b5/as
    #PF_OIDC_CLIENT_AUTHN_METHOD: client_secret_basic
    #PF_OIDC_SCOPES: openid email profile
    #PF_OIDC_USERNAME_ATTRIBUTE_NAME: name
    #PF_OIDC_ROLE_ATTRIBUTE_NAME: pf_admin_roles
    #PF_OIDC_ROLE_ADMIN: fullAdmin
    #PF_OIDC_ROLE_CRYPTOMANAGER: fullAdmin
    #PF_OIDC_ROLE_USERADMIN: fullAdmin
    #PF_OIDC_ROLE_EXPRESSIONADMIN: fullAdmin
    #PF_OIDC_ACR_VALUES: ""

  services:
    https:
      servicePort: 9999
      containerPort: 9999
      ingressPort: 443
      dataService: true
    engine:
      servicePort: 9031
      containerPort: 9031
      ingressPort: 443
      dataService: true

  ingress:
    hosts:
      - host: pingfederate-admin._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
      - host: pingfederate-engine._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: engine
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingfederate-admin._defaultDomain_
          - pingfederate-engine._defaultDomain_


#############################################################
# pingfederate-engine values
#############################################################
# pingfederate-engine:
#   enabled: false
#   name: pingfederate-engine
#   image:
#     name: pingfederate

#   container:
#     resources:
#       requests:
#         cpu: 0
#         memory: 1Gi
#       limits:
#         cpu: 2
#         memory: 4Gi
#     waitFor:
#       pingfederate-admin:
#         service: https
#         timeoutSeconds: 300

#   envs:
#     SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
#     SERVER_PROFILE_PATH: server-profiles/pingfederate
# #     PF_ADMIN_PORT: "9999"

#   services:
#     https:
#       servicePort: 9031
#       containerPort: 9031
#       ingressPort: 443
#       dataService: true
#     clusterbind:
#       servicePort: 7600
#       containerPort: 7600
#       clusterService: true
#     clusterfail:
#       servicePort: 7700
#       containerPort: 7700
#       clusterService: true
#     clusterServiceName: pingfederate-cluster

#   ingress:
#     hosts:
#       - host: pingfederate-engine._defaultDomain_
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             serviceName: https
#     tls:
#       - secretName: _defaultTlsSecret_
#         hosts:
#           - pingfederate-engine._defaultDomain_

#############################################################
# pingdirectory values
#############################################################
pingdirectory:
  enabled: true
  name: pingdirectory
  image:
    name: pingdirectory

  container:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi

    terminationGracePeriodSeconds: 300

    probes:
      readinessProbe:
        periodSeconds: 30
        failureThreshold: 4
      startupProbe:
        periodSeconds: 10
        failureThreshold: 180

  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        volumes:
          out-dir:
            persistentVolumeClaim:
              resources:
                requests:
                  storage: 8Gi

  envs:
    SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
    SERVER_PROFILE_PATH: server-profiles/pingdirectory
    MAKELDIF_USERS: "10"

  services:
    ldap:
      servicePort: 389
      containerPort: 1389
      dataService: true
    ldaps:
      servicePort: 636
      containerPort: 1636
      dataService: true
      clusterService: true
    https:
      servicePort: 443
      containerPort: 1443
      ingressPort: 443
      dataService: true
    clusterServiceName: pingdirectory-cluster

  ingress:
    hosts:
      - host: pingdirectory._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingdirectory._defaultDomain_


#############################################################
# pingaccess-admin values
#############################################################
pingaccess-admin:
  enabled: false
  name: pingaccess-admin
  image:
    name: pingaccess

  # container:
  #   resources:
  #     requests:
  #       cpu: 0
  #       memory: 1Gi
  #     limits:
  #       cpu: 2
  #       memory: 4Gi

  envs:
    # SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    # SERVER_PROFILE_PATH: getting-started/pingaccess
    SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
    SERVER_PROFILE_PATH: server-profiles/pingaccess
    OPERATIONAL_MODE: STANDALONE

  # workload:
  #   type: StatefulSet
  #   statefulSet:
  #     persistentvolume:
  #       volumes:
  #         out-dir:
  #           persistentVolumeClaim:
  #             resources:
  #               requests:
  #                 storage: 8Gi

  services:
    https:
      servicePort: 9000
      containerPort: 9000
      ingressPort: 443
      dataService: true
    engine:
      servicePort: 3000
      containerPort: 3000
      ingressPort: 443
      dataService: true
  # clusterconfig:
  #   servicePort: 9090
  #   containerPort: 9090
  #   dataService: true

  ingress:
    hosts:
      - host: pingaccess-admin._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
      - host: pingaccess-engine._defaultDomain_
        paths:
        - path: /
          backend:
            serviceName: engine
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingaccess-admin._defaultDomain_
          - pingaccess-engine._defaultDomain_

#############################################################
# pingaccess-engine values
#############################################################
# pingaccess-engine:
#   enabled: false
#   name: pingaccess-engine
#   image:
#     name: pingaccess

#   container:
#     resources:
#       requests:
#         cpu: 0
#         memory: 1Gi
#       limits:
#         cpu: 2
#         memory: 4Gi
#     waitFor:
#       pingaccess-admin:
#         service: https
#         timeoutSeconds: 300

#   envs:
#     SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
#     SERVER_PROFILE_PATH: getting-started/pingaccess
#     #SERVER_PROFILE_URL: https://github.com/greggpingidentity/silver-penguin.git
#     #SERVER_PROFILE_PATH: server-profiles/pingaccess

#   services:
#     https:
#       servicePort: 3000
#       containerPort: 3000
#       ingressPort: 443
#       dataService: true

#   ingress:
#     hosts:
#       - host: pingaccess-engine._defaultDomain_
#         paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             serviceName: https
#     tls:
#       - secretName: _defaultTlsSecret_
#         hosts:
#           - pingaccess-engine._defaultDomain_

#############################################################
# pingdataconsole values
#############################################################
pingdataconsole:
  enabled: true
  name: pingdataconsole
  image:
    name: pingdataconsole

  container:
    resources:
      requests:
        cpu: 0
        memory: .5Gi
      limits:
        cpu: 2
        memory: 2Gi

  defaultLogin:
    server:
      host: pingdirectory-cluster
      port: 636
    username: administrator

  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    SERVER_PROFILE_PATH: baseline/pingdataconsole

  services:
    https:
      containerPort: 8443
      servicePort: 8443
      ingressPort: 443
      dataService: true

  ingress:
    hosts:
      - host: pingdataconsole._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingdataconsole._defaultDomain_